### ISSUE TITLE
Best supported OS?

### ISSUE THREAD

**Issue by wh5a** [qucat/qucat#67] opened 2020-01-10 01:10 UTC
What's the best system to run this program, Windows or Linux? I tried it on Mac Catalina, and the GUI doesn't seem to function correctly. Specifically, only capacitors are drawn. Other types of components don't have their graphical representation drawn at all. I can see the values and the labels, and I can drag them around, but they are only displayed as something invisible between two dots.

**Comment by mgely** [comment] 2020-01-10 13:54
It's developed on Windows, and as far as I know there are no bugs in the GUI on either windows or linux. 

Unfortunately Tkinter has some incompatibilities with certain Mac OSs, and I already tailored certain parts of the code to different versions of the OS. From what you say there are more problems with the latest version and I will take a look at these issues shortly. 

Thanks for letting me know, I was not aware of this problem!

**Comment by mgely** [comment] 2020-01-30 14:07
Dear @wh5a, I just tried using QuCAT on Catalina 10.15.2, and I could not reproduce this bug. 
Do you have an up to date version of python 3 and of the libraries QuCAT relies upon?
Maybe try creating a new conda environment, pip installing QuCAT and check if the bug is still present.
What specific version of Catalina do you have?

**Comment by AdriaanRol** [comment] 2020-09-03 08:21
I had similar issues with the GUI on Catalina 10.15.5 all components are invisible with the exception of wires. I'll dig a bit deeper to find out what's going on.

**Comment by gsteele13** [comment] 2021-05-12 14:31
I've been using it lately on Big Sur 11.2.3 and things seem to work?

**Comment by gsteele13** [comment] 2021-05-12 14:32
(ultimately, we'd love to move the GUI into a jupyter widget, but will require some gui programming and I'm not sure what toolkit would make sense...)

**Comment by gsteele13** [comment] 2021-05-12 14:33
@AdriaanRol @wh5a Can you guys check if these are still issues? If not, I'll close this issue to keep our issue tracker a bit clean

**Comment by gsteele13** [comment] 2021-05-12 14:41
actually, i'll just close this, please reopen if still relevant. i feel we need to get rid of tkinter...

**Closed by gsteele13** 2021-05-12 14:41 UTC
